#!/usr/bin/env bash
# load balancer lb-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/.ssh/school

# Username and IP Address 
ssh ubuntu@54.237.63.92
